version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      DJANGO_DEBUG: "1"
      DJANGO_SECRET_KEY: "your-very-secret-key-here"  # замени на свой реальный секретный ключ
    restart: always
    command: gunicorn mysite.wsgi:application --bind 0.0.0.0:8000